### ISSUE TITLE
Getting `cardinalityViolation` and `isOnClosedChannel` when trying to send new request

### ISSUE THREAD

**Issue by khairilushan** [grpc/grpc-swift#751] opened 2020-03-17 09:30 UTC
So I have this kind of service class that wrap the swift-grpc `BidirectionalStreamingCall`. But I keep getting `cardinalViolation` and then followed by `isOnClosedChannel` when I try to call `requestNearbyCars` for the **second** time.

```
import Foundation
import GRPC
import NIO
import NIOHPACK
import RxSwift
import RxCocoa

public final class NearbyCarService: Service {

	typealias GetNearbyCarStreamCall = BidirectionalStreamingCall<Protobuf_NearbyCarsRequest, Protobuf_NearbyCarsResponse>

	public let nearbyCars = BehaviorRelay<[Car]>(value: [])
	
	public var requestNearbyCarErrorObservable: Observable<Error> {
		return _requestNearbyCarErrorObservable.asObservable()
	}
	
	private let _requestNearbyCarErrorObservable = PublishSubject<Error>()
	
	private var currentNearbyCarsCaller: GetNearbyCarStreamCall?
	private var isStreamingStoped = false

	private let group = MultiThreadedEventLoopGroup(numberOfThreads: 1)
	private let callOptions: CallOptions
	private let grpcService: Protobuf_LocationServiceService
	
	public init(buildLevel: BuildLevel, accessToken: String) {
		
		let configuration = ChannelDataFactory.configurations(for: buildLevel, group: group)
		let connection = ClientConnection(configuration: configuration)
		let tokenHeader = [ ("token", accessToken) ]
		let headers = NIOHPACK.HPACKHeaders(tokenHeader)

		callOptions = CallOptions(customMetadata: headers, timeout: .default)

		grpcService = Protobuf_LocationServiceServiceClient(channel: connection, defaultCallOptions: callOptions)
	}
	
	deinit {
		try? self.group.syncShutdownGracefully()
	}
	
	// MARK: - Public methods
	
	public func requestNearbyCars(location: Location, serviceTypeID: Int) {

		let request = Protobuf_NearbyCarsRequest(
			location: location,
			serviceTypeID: serviceTypeID
		)
		
		requestNearbyCars(request: request)
	}
	
	public func stopStreaming() {
		isStreamingStoped = true
	}

	
	// MARK: - Private methods
	
	private func requestNearbyCars(request: Protobuf_NearbyCarsRequest)  {

		isStreamingStoped = false

		createCallerIfNeeded()

		currentNearbyCarsCaller?.sendMessage(request)
			.whenFailure { [weak self] (error: Error) in
				self?._requestNearbyCarErrorObservable.onNext(error)
			}
	}

	private func createCallerIfNeeded() {

		guard currentNearbyCarsCaller == nil else {
			return
		}

		currentNearbyCarsCaller = grpcService.getNearbyCars(
			callOptions: callOptions,
			handler: { [weak self] (response: Protobuf_NearbyCarsResponse) in

				guard self?.isStreamingStoped == false else {
					return
				}

				self?.handleSuccessResponse(response)
			}
		)
	}
	
	private func handleSuccessResponse(_ response: Protobuf_NearbyCarsResponse) {
	
		let cars = response.cars.compactMap { (protobufCar: Protobuf_Car) -> Car? in
			return Car(protobufCar: protobufCar)
		}

		nearbyCars.accept(cars)
	}
	
}
```

**Comment by glbrntt** [comment] 2020-03-17 10:28
You'd get a cardinality violation if you send a message when the client has already closed its request stream. Are you calling `sendEnd()` anywhere? Alternatively the channel may have caught an error and closed the channel. 

Can you upload logs at debug level?

**Comment by khairilushan** [comment] 2020-03-17 10:39
I don't have any `sendEnd` code right now. And the only log that shown in my Xcode console is bunch of info like this one:
```
info: remote_address=[IPv4]x.x.x.x/x.x.x.:yyyy connection_id=B6FB6316-BC48-41A0-86B8-6F0CFFC9BFCE event_loop=SelectableEventLoop { selector = Selector { descriptor = 10 }, thread = NIOThread(name = NIO-ELT-0-#0) } gRPC connection ready
```

**Comment by glbrntt** [comment] 2020-03-17 10:41
Can you enable debug logging?

```swift
import Logging

// make sure this is only called once, at startup:
LoggingSystem.bootstrap {
  var handler = StreamLogHandler.standardOutput(label: $0)
  handler.logLevel = .debug
  return handler
}
```

**Comment by khairilushan** [comment] 2020-03-17 10:53
Here is the debug log output
```
2020-03-17T17:49:46+0700 debug: connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 target=hostAndPort("host.name", 9999) event_loop=SelectableEventLoop { selector = Selector { descriptor = 22 }, thread = NIOThread(name = NIO-ELT-0-#0) } attempting to connect
2020-03-17T17:49:46+0700 debug: connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 old_state=idle new_state=connecting connectivity state change
2020-03-17T17:49:46+0700 debug: connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 server-hostname=host.name using host from connection target for TLS
2020-03-17T17:49:46+0700 debug: connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 making client bootstrap with event loop group of type SelectableEventLoop
2020-03-17T17:49:46+0700 debug: connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 Network.framework is available but the group is not typed for NIOTS, falling back to ClientBootstrap
2020-03-17T17:49:46+0700 debug: connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 creating a ClientBootstrap
2020-03-17T17:49:46+0700 debug: timeout_seconds=20.0 connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 setting connect timeout
2020-03-17T17:49:46+0700 debug: path=/protobuf.LocationService/GetNearbyCars request_id=1397D230-ABE4-4EA2-BE93-C925E76D347D connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 starting rpc
2020-03-17T17:49:46+0700 debug: connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 TLS handshake completed, negotiated protocol: h2
2020-03-17T17:49:46+0700 debug: connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 observed initial settings frame on the root stream
2020-03-17T17:49:46+0700 debug: connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 new_state=ready old_state=connecting connectivity state change
2020-03-17T17:49:46+0700 debug: connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 removing 'InitialSettingsObservingHandler' from the channel
2020-03-17T17:50:16+0700 debug: duration_ms=30184 request_id=1397D230-ABE4-4EA2-BE93-C925E76D347D connection_id=49A9C844-3D4A-495B-947F-E2CC56CE66A0 status_code=0 rpc call finished
```

**Comment by glbrntt** [comment] 2020-03-17 10:58
Right, the RPC completes with `status_code=0` (ok). Is this your server? I would assume that the server is terminating the RPC here.

**Comment by khairilushan** [comment] 2020-03-17 11:04
Hmm weird, because this didn't happen in my app when I still using the very old version of swift-grpc. 
Anyway, if the RPC is completed, then I should re-initialise the `grpcService` instance and execute the `grpcService.getNearbyCars(...)` again?

**Comment by khairilushan** [comment] 2020-03-17 11:14
is there any listener/callback so that I get notified when the RPC is completed ?

**Comment by glbrntt** [comment] 2020-03-17 11:21
In that case we should debug this so we understand where the problem is coming from. 

Could you set a breakpoint [here](https://github.com/grpc/grpc-swift/blob/nio/Sources/GRPC/GRPCClientStateMachine.swift#L472) and then print `self` and `trailers` when you hit it?

**Comment by glbrntt** [comment] 2020-03-17 11:21
> is there any listener/callback so that I get notified when the RPC is completed ?

Yes: the `status` future on the rpc, i.e. `currentNearbyCarsCaller.status`

**Comment by khairilushan** [comment] 2020-03-17 11:36
> In that case we should debug this so we understand where the problem is coming from.
> 
> Could you set a breakpoint [here](https://github.com/grpc/grpc-swift/blob/nio/Sources/GRPC/GRPCClientStateMachine.swift#L472) and then print `self` and `trailers` when you hit it?

I tried this, but when I try to print `self` and `trailers`, there is no result. When I tried to `right click + print description` of self or trailers, My Xcode just stoped the debugging session 😓 

But at least for now, whe I get the rpc finish, I can work around this by recreate the `currentNearbyCarsCaller` and execute `getNearbyCars` again.

**Comment by khairilushan** [comment] 2020-03-17 11:37
> > is there any listener/callback so that I get notified when the RPC is completed ?
> 
> Yes: the `status` future on the rpc, i.e. `currentNearbyCarsCaller.status`

Thank you for this one, will try to use this on my workaround.

And thank you for always helping on all my swift-grpc question. 🙏

**Closed** 2020-03-18 00:35 UTC
Labels: needs more info, nio
