### ISSUE TITLE
Crash in ConnectionManager.channelError

### ISSUE THREAD

**Issue by DenTelezhkin** [grpc/grpc-swift#1194] opened 2021-05-28 10:20 UTC
### Describe the bug

Hi!

We are receiving a bunch of crashes through our crash reporting tool, that we cannot currently reproduce locally on our development machines. This crash is similar to #874, however we are using 1.0.0 version of grpc-swift, so it should be fixed there. Would appreciate any help in resolving this issue. 

grpc-swift version: 1.0.0
protoc-gen-grpc-swift version: v3.14.0

Crashes happen on macOS Big Sur(although it might be because our users are mostly on Big Sur.)

### To reproduce

Unfortunately, can't reproduce at the moment.

### Expected behaviour

App should not crash.

### Additional information

Crash log:

```
OS Version: macOS 11.3.1 (20E241)
Report Version: 104

Exception Type: EXC_BAD_INSTRUCTION (SIGILL)
Exception Codes: ILL_NOOP at 0x000000010c63cdcd
Crashed Thread: 6

Application Specific Information:
Exception 2, Code 0, Subcode 8

Thread 6 Crashed:
0   <Redacted>                         0x10c63cdcd         ConnectionManager.channelError
1   <Redacted>                          0x10c65d03b         GRPCIdleHandler
2   <Redacted>                          0x10c6df145         ChannelHandlerContext.invokeErrorCaught
3   <Redacted>                          0x10c6d36e2         _ChannelInboundHandler.errorCaught
4   <Redacted>                          0x10c6df145         ChannelHandlerContext.invokeErrorCaught
5   <Redacted>                          0x10c6d36e2         _ChannelInboundHandler.errorCaught
6   <Redacted>                          0x10c6df145         ChannelHandlerContext.invokeErrorCaught
7   <Redacted>                          0x10c6d36e2         _ChannelInboundHandler.errorCaught
8   <Redacted>                          0x10c6df145         ChannelHandlerContext.invokeErrorCaught
9   <Redacted>                          0x10c6de44d         ChannelPipeline.fireErrorCaught
10  <Redacted>                          0x10c784918         NIOTSConnectionChannel.dataReceivedHandler
11  libswiftNetwork.dylib           0xfffeaa869abf      NWConnection.receiveMessage
12  libswiftNetwork.dylib           0xfffeaa8697c3      @callee_guaranteed
13  libdispatch.dylib               0xfffe405c917d      _dispatch_block_async_invoke2
14  libdispatch.dylib               0xfffe405bc7e5      _dispatch_client_callout
15  libdispatch.dylib               0xfffe405c25c9      _dispatch_lane_serial_drain
16  libdispatch.dylib               0xfffe405c30bf      _dispatch_lane_invoke
17  libdispatch.dylib               0xfffe405c2472      _dispatch_lane_serial_drain
18  libdispatch.dylib               0xfffe405c30bf      _dispatch_lane_invoke
19  libdispatch.dylib               0xfffe405ccbec      _dispatch_workloop_worker_thread
20  libsystem_pthread.dylib         0xfffe4090a4bf      _pthread_wqthread
21  libsystem_pthread.dylib         0xfffe40909492      start_wqthread

Thread 0
0   libsystem_kernel.dylib          0xfffe408a832a      mach_msg_trap
1   CoreFoundation                  0xfffe40a84c6e      __CFRunLoopServiceMachPort
2   CoreFoundation                  0xfffe40a8334e      __CFRunLoopRun
3   CoreFoundation                  0xfffe40a8275b      CFRunLoopRunSpecific
4   HIToolbox                       0xfffe50f14202      RunCurrentEventLoopInMode
5   HIToolbox                       0xfffe50f13f64      ReceiveNextEventCommon
6   HIToolbox                       0xfffe50f13d02      _BlockUntilNextEventMatchingListInModeWithFilter
7   AppKit                          0xfffe45abbb31      _DPSNextEvent
8   AppKit                          0xfffe45aba304      -[NSApplication(NSEvent) _nextEventMatchingEventMask:untilDate:inMode:dequeue:]
9   AppKit                          0xfffe45aac678      -[NSApplication run]
10  AppKit                          0xfffe45a8085b      NSApplicationMain
11  <Redacted>                         0x20c1305d7         main (main.swift:27)
12  libdyld.dylib                   0xfffe40934f3c      start

Thread 1
0   libsystem_kernel.dylib          0xfffe408aac22      __semwait_signal
1   libsystem_c.dylib               0xfffe40735a91      sleep
2   CrashReporting                  0x10c38b8b6         monitorCachedData
3   libsystem_pthread.dylib         0xfffe4090d953      _pthread_start
4   libsystem_pthread.dylib         0xfffe409094a6      thread_start

Thread 2 name: SentryCrash Exception Handler (Secondary)
0   libsystem_kernel.dylib          0xfffe408a832a      mach_msg_trap
1   CrashReporting                  0x10c3871b2         handleExceptions
2   libsystem_pthread.dylib         0xfffe4090d953      _pthread_start
3   libsystem_pthread.dylib         0xfffe409094a6      thread_start

Thread 4 name: com.apple.NSURLConnectionLoader
0   libsystem_kernel.dylib          0xfffe408a832a      mach_msg_trap
1   CoreFoundation                  0xfffe40a84c6e      __CFRunLoopServiceMachPort
2   CoreFoundation                  0xfffe40a8334e      __CFRunLoopRun
3   CoreFoundation                  0xfffe40a8275b      CFRunLoopRunSpecific
4   CFNetwork                       0xfffe491e5cdb      _CFURLStorageSessionCopyCache
5   Foundation                      0xfffe425af976      __NSThread__start__
6   libsystem_pthread.dylib         0xfffe4090d953      _pthread_start
7   libsystem_pthread.dylib         0xfffe409094a6      thread_start

Thread 5 name: com.apple.NSEventThread
0   libsystem_kernel.dylib          0xfffe408a832a      mach_msg_trap
1   SkyLight                        0xfffe49a25164      CGSSnarfAndDispatchDatagrams
2   SkyLight                        0xfffe49cc41c3      SLSGetNextEventRecordInternal
3   SkyLight                        0xfffe49b1b024      SLEventCreateNextEvent
4   HIToolbox                       0xfffe50f212ad      PullEventsFromWindowServerOnConnection
5   HIToolbox                       0xfffe50f21167      MessageHandler
6   CoreFoundation                  0xfffe40ab1241      __CFMachPortPerform
7   CoreFoundation                  0xfffe40a85213      __CFRUNLOOP_IS_CALLING_OUT_TO_A_SOURCE1_PERFORM_FUNCTION__
8   CoreFoundation                  0xfffe40a850f4      __CFRunLoopDoSource1
9   CoreFoundation                  0xfffe40a8377e      __CFRunLoopRun
10  CoreFoundation                  0xfffe40a8275b      CFRunLoopRunSpecific
11  AppKit                          0xfffe45c41ba9      _NSEventThread
12  libsystem_pthread.dylib         0xfffe4090d953      _pthread_start
13  libsystem_pthread.dylib         0xfffe409094a6      thread_start

Thread 6 Crashed:
0   <Redacted>                          0x10c63cdcd         ConnectionManager.channelError
1   <Redacted>                          0x10c65d03b         GRPCIdleHandler
2   <Redacted>                          0x10c6df145         ChannelHandlerContext.invokeErrorCaught
3   <Redacted>                          0x10c6d36e2         _ChannelInboundHandler.errorCaught
4   <Redacted>                          0x10c6df145         ChannelHandlerContext.invokeErrorCaught
5   <Redacted>                          0x10c6d36e2         _ChannelInboundHandler.errorCaught
6   <Redacted>                          0x10c6df145         ChannelHandlerContext.invokeErrorCaught
7   <Redacted>                          0x10c6d36e2         _ChannelInboundHandler.errorCaught
8   <Redacted>                          0x10c6df145         ChannelHandlerContext.invokeErrorCaught
9   <Redacted>                          0x10c6de44d         ChannelPipeline.fireErrorCaught
10  <Redacted>                          0x10c784918         NIOTSConnectionChannel.dataReceivedHandler
11  libswiftNetwork.dylib           0xfffeaa869abf      NWConnection.receiveMessage
12  libswiftNetwork.dylib           0xfffeaa8697c3      @callee_guaranteed
13  libdispatch.dylib               0xfffe405c917d      _dispatch_block_async_invoke2
14  libdispatch.dylib               0xfffe405bc7e5      _dispatch_client_callout
15  libdispatch.dylib               0xfffe405c25c9      _dispatch_lane_serial_drain
16  libdispatch.dylib               0xfffe405c30bf      _dispatch_lane_invoke
17  libdispatch.dylib               0xfffe405c2472      _dispatch_lane_serial_drain
18  libdispatch.dylib               0xfffe405c30bf      _dispatch_lane_invoke
19  libdispatch.dylib               0xfffe405ccbec      _dispatch_workloop_worker_thread
20  libsystem_pthread.dylib         0xfffe4090a4bf      _pthread_wqthread
21  libsystem_pthread.dylib         0xfffe40909492      start_wqthread

Thread 7
0   libsystem_kernel.dylib          0xfffe408a99ce      __workq_kernreturn
1   libsystem_pthread.dylib         0xfffe40909492      start_wqthread

Thread 8
0   libsystem_kernel.dylib          0xfffe408a99ce      __workq_kernreturn
1   libsystem_pthread.dylib         0xfffe40909492      start_wqthread



EOF
```

**Comment by glbrntt** [comment] 2021-05-28 13:15
This looks like a dupe of https://github.com/grpc/grpc-swift/issues/1132 which should be fixed by https://github.com/grpc/grpc-swift/pull/1133. It's not in a tagged release yet but hoping to get a release out the door soon.

**Comment by miyaeyo** [comment] 2021-06-08 06:47
We have same crash and we are using 1.0.0 version of grpc-swift too. 
I want to know when fixed version will be released.

**Comment by glbrntt** [comment] 2021-06-08 13:31
[1.1.0](https://github.com/grpc/grpc-swift/releases/tag/1.1.0) has just been released. @DenTelezhkin please reopen if this doesn't fix your issue!

**Closed by glbrntt** 2021-06-08 13:31 UTC
Labels: bug

**Comment by DenTelezhkin** [comment] 2021-06-10 13:56
We did not have a chance to try 1.1.0 out, but I can confirm that at least using ec8e5e0b817d292de98b33dee75be83aee9e1e2c commit fixes this crash!

Thanks a lot!
