### ISSUE TITLE
Problem for distribution when cocoapods is used ?

### ISSUE THREAD

**Issue by xavierpecheur** [grpc/grpc-swift#1274] opened 2021-09-24 16:20 UTC
I should want to use the gRPC-Swift in a project but when I want to build it, the compilation crashed on the internal dependencies.

### Describe the bug

Build crashed on _NIODataStructures.
Several errors : 'self' used before 'self.init' call or assignment to 'self'

![Capture d’écran 2021-09-24 à 14 53 18](https://user-images.githubusercontent.com/13733180/134708148-36ca5aa2-0472-4b25-b32e-985d7ec5a18f.png)

### To reproduce

1. Create new simple AR project
2. In the directory of this new project, launch `pod init` and `pod install`
3. Open the workspace
4. Add to Podfile:
```
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'
use_frameworks!
inhibit_all_warnings!

target 'testgRPC2' do
  pod ‘gRPC-Swift’
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings["IPHONEOS_DEPLOYMENT_TARGET"] = "13.0"
      config.build_settings["BUILD_LIBRARY_FOR_DISTRIBUTION"] = "YES"
      config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
    end
  end
end
```
5. Close project
6. Remove .xcworkspace
7. Launch again `pod install`
8. Open workspace
9. Try to build the App

### Expected behaviour

Successful compilation.

When I comment on the line  `config.build_settings["BUILD_LIBRARY_FOR_DISTRIBUTION"] = "YES"`, the build works

### Additional information

macOS Big Sur Version 11.2.3
Xcode 12.5.1
Apple Swift version 5.4.2 (swiftlang-1205.0.28.2 clang-1205.0.19.57)

**Comment by Lukasa** [comment] 2021-09-24 16:46
Thanks for filing this issue! This is a duplicate of #1063, which remains the most up-to-date reference on our thinking around BUILD_LIBRARY_FOR_DISTRIBUTION.

**Closed by Lukasa** 2021-09-24 16:46 UTC
Labels: bug
