### ISSUE TITLE
Fail fast

### ISSUE THREAD

**Issue by moh-abk** [grpc/grpc-swift#1085] opened 2020-12-16 22:13 UTC
### What are you trying to achieve?

I've setup my iOS app to first fetch data from the backend api -> persist to coredata and then present coredata -> UI. This is in order to support offline mode.

### What have you tried so far?

I setup the client like so;

```
let channel = ClientConnection
            .secure(group: group)
            .withCallStartBehavior(.fastFailure)
            .connect(host: "api.backend.com", port: 443)
```

I also have `timeLimit: TimeLimit.timeout(.seconds(120))` in **callOptions**

If I receive an error make the backend api call I immediate revert back to fetch stale data from coredata.

```
    func refreshFromBackend(id: String) -> AnyPublisher<Void, Error> {
        return gateway
            .getBackendObject(id: id)
            .map { response in
                BackendObject(protoObject: response.object)!
            }.
            .catch { err in <------------------------- any failure relating from backend return from coredata
                // must return a Publisher
                repository.object(id: id)
                
            }
            .flatMap { [repository] in <------------------------- store in coredata
                repository.store(object: $0!)
            }
            .eraseToAnyPublisher()
    }
```

I would expect `withCallStartBehavior(.fastFailure)` to fail after some specified time? I feel like I'm missing some other config that will say after 5s of no connectivity either by flaky connection or Airplane mode

Any guidance appreciated.

Version: `1.0.0-alpha.21`

**Comment by glbrntt** [comment] 2020-12-17 08:53
The RPC will only fail quickly if the connection state is in the transient failure state. If the state is idle or connecting then you have to wait for the connection attempt to be completed, which could take up to 20 seconds (the default connection timeout).

It sounds like you're after the behavior described in https://github.com/grpc/grpc-swift/issues/985?

**Comment by moh-abk** [comment] 2020-12-17 16:27
> The RPC will only fail quickly if the connection state is in the transient failure state. If the state is idle or connecting then you have to wait for the connection attempt to be completed, which could take up to 20 seconds (the default connection timeout).
> 
> It sounds like you're after the behavior described in #985?

Yes - is there an ETA? 😅

**Comment by glbrntt** [comment] 2020-12-18 08:34
No; this isn't a high priority right now. Closing this as a dupe of #985.

**Closed by glbrntt** 2020-12-18 08:34 UTC
Labels: duplicate, question
