### ISSUE TITLE
unknownParameter(name: "AsyncClient") and unknownParameter(name: "AsyncServer")

### ISSUE THREAD

**Issue by JanTG1** [grpc/grpc-swift#1472] opened 2022-08-11 10:02 UTC
### What are you trying to achieve?

I am trying to generate proto files with the new async feature. In the past, I have always generated my protos in the following manner: 
protoc Protos/Car.proto \     
                --proto_path=Protos/ \
                --plugin=Pods/gRPC-Swift-Plugins/bin/protoc-gen-swift \
                --plugin=Pods/gRPC-Swift-Plugins/bin/protoc-gen-grpc-swift \
                --swift_opt=Visibility=Public \
                --swift_out=Client.Swift/Client_Swift.docc/Generated/ \
                --grpc-swift_out=Client.Swift/Client_Swift.docc/Generated/ \
                --grpc-swift_opt=Visibility=Public

This has always worked well. With the support for Async GRPC, I wanted to update my protos to support them. I followed your basic tutorial and found out that I had to add AsyncClient=True and AsyncServer=True to the command. It now looks like this:

protoc Protos/Car.proto \             
                --proto_path=Protos/ \
                --plugin=Pods/gRPC-Swift-Plugins/bin/protoc-gen-swift \
                --plugin=Pods/gRPC-Swift-Plugins/bin/protoc-gen-grpc-swift \
                --swift_opt=Visibility=Public \
                --swift_out=Client.Swift/Client_Swift.docc/Generated/ \
                --grpc-swift_out=Client.Swift/Client_Swift.docc/Generated/ \
                --grpc-swift_opt=Visibility=Public,AsyncClient=True,AsyncServer=True

However, Terminal always throws the following error: 
unknownParameter(name: "AsyncClient")

When removing AsyncClient=True, it returns unknownParameter(name: "AsyncServer")

### What have you tried so far?

I have tried everything I could think of: I have updated everything from home brew to the grpc-swift pods. I am now using the newest 1.19.0. I have also updated the protobuf compiler to 3.21.5. I have changed my terminal command to look more like yours and have restarted my mac after updating everything. I have even installed grpc using the package manager instead of cocoapods. Nothing changed, the error persists.

What am I doing wrong? Might this be an unknown issue?

**Comment by Lukasa** [comment] 2022-08-11 10:11
The `AsyncClient` and `AsyncServer` parameters are no longer necessary as of 1.8.0. Dupe of #1464.

**Closed by Lukasa** 2022-08-11 10:11 UTC
Labels: question
