### ISSUE TITLE
Detecting request failure when offline/no connection

### ISSUE THREAD

**Issue by IgorRosocha** [grpc/grpc-swift#831] opened 2020-06-09 09:35 UTC
### What are you trying to achieve?

I am using 1.0.0-alpha.12 release. I need to detect when request fails because of connection error. Currently, when connection error occurs, the request is retried, but result/error is not received, thus the response completion block is not fired, so I am unable to detect the failure of request.

Sample code:

```swift
let call = requestFunction(request, callOptions).response.always { result in
    switch result {
    case let .success(value):
        // Handle success
    case let .failure(error):
        // Handle failure/error
    }
}
```
Is there a way to detect and handle failure/error first time the request fails because of a connection error (or maybe after a few retries/seconds)?

### What have you tried so far?

I have tried to use `.whenFailure` on `response` and also adjust [Connection Backoff](https://github.com/grpc/grpc/blob/master/doc/connection-backoff.md), but I am unable to receive and handle failure on connection error.

**Comment by glbrntt** [comment] 2020-06-09 11:04
> Currently, when connection error occurs, the request is retried, but result/error is not received, thus the response completion block is not fired, so I am unable to detect the failure of request.

I just want to clear some things up: gRPC will not retry any _requests_ for you.

However, if there is a connection error before the RPC has started, then gRPC will attempt to re-establish a connection (unless you have disabled connection re-establishment) and will then try to make the request. If the connection fails _after_ the RPC has started then the response, metadata and status futures will be failed (unless they have already succeeded).

> Is there a way to detect and handle failure/error first time the request fails because of a connection error (or maybe after a few retries/seconds)?

The above code _should_ work and the error should be a `GRPCStatus` with the `.unavailable` status code if the call failed because of a connection error.

Are you sure that the completion is _never_ fired or just takes a long time to fire? The default connection timeout is 20 seconds (it can be larger than this as the backoff between attempts increases). It may just be the case that you're hitting the 20 seconds. You can configure the minimum connection timeout to use in the connection builder:

https://github.com/grpc/grpc-swift/blob/dca180f7f7f3bdd495d294ca2a463a82b5e33900/Sources/GRPC/GRPCChannel/GRPCChannelBuilder.swift#L113

Or directly as part of the `ConnectionBackoff` which is passed to the `ClientConnection.Configuration`:

https://github.com/grpc/grpc-swift/blob/dca180f7f7f3bdd495d294ca2a463a82b5e33900/Sources/GRPC/ConnectionBackoff.swift#L79

**Comment by glbrntt** [comment] 2020-06-09 12:26
> @glbrntt thanks for your fast reply and for clearing things up 🙂
> 
> > Are you sure that the completion is never fired or just takes a long time to fire? The default connection timeout is 20 seconds (it can be larger than this as the backoff between attempts increases). It may just be the case that you're hitting the 20 seconds.
> 
> Yes, the completion is not fired even after a few minutes. All I'm getting is console output like this:

Yikes, that's definitely a bug then!

Do you know if this reproduces with 1.0.0-alpha.13? The connection management was rewritten so I'd be curious to bug still exists.

**Comment by IgorRosocha** [comment] 2020-06-11 10:48
> Do you know if this reproduces with 1.0.0-alpha.13? The connection management was rewritten so I'd be curious to bug still exists.

Unfortunately, the issue reproduces with 1.0.0-alpha.14. Console output has slightly changed:

`info: old_state=connecting new_state=transientFailure connection_id=A8057028-F580-44B5-B2AF-198781760A22/0 connectivity state change`

**Comment by glbrntt** [comment] 2020-06-11 13:37
@IgorRosocha I wasn't able to repro this. Can you provide more details on how to reproduce this, i.e. what platforms are you running on? Is it your own server? Is it a grpc-swift server? How are you dropping the connection?

**Comment by IgorRosocha** [comment] 2020-06-12 07:17
@glbrntt To reproduce this, I just drop the device connection and try to make requests from app. It is our own server implementation. I am dropping the connection by putting device into the flight mode, but have also tried turning off all the network services. Same results, the completion doesn't get fired. You can see the GPRC clients initialization code above.

Please let me know if I can provide more information/detail.

**Comment by glbrntt** [comment] 2020-06-12 07:47
Okay, knowing it's an iOS app is helpful! Can you clarify what part of the server is your own implementation, the whole server? Or just the service handler (i.e. business logic)? If it's the latter, what grpc framework are you using for the server?

As a side note we *strongly* recommend that when using iOS you create an event loop group using `PlatformSupport.makeEventLoopGroup(loopCount:)` -- you'll get the Network.framework based implementation (when it's supported, falling back to the sockets implementation when it isn't). See also https://github.com/grpc/grpc-swift/blob/master/docs/apple-platforms.md.

**Comment by IgorRosocha** [comment] 2020-06-12 08:43
> Okay, knowing it's an iOS app is helpful! Can you clarify what part of the server is your own implementation, the whole server? Or just the service handler (i.e. business logic)? If it's the latter, what grpc framework are you using for the server?

The latter. We're using [mali.js](https://mali.js.org/) server framework.

> As a side note we strongly recommend that when using iOS you create an event loop group using PlatformSupport.makeEventLoopGroup(loopCount:) -- you'll get the Network.framework based implementation (when it's supported, falling back to the sockets implementation when it isn't). See also https://github.com/grpc/grpc-swift/blob/master/docs/apple-platforms.md.

I have tried using event loop group like this, but we had some issues with failing request after going from offline to online state. Nevertheless, issue still persists.

**Comment by glbrntt** [comment] 2020-06-12 11:55
I just re-read this thread and realised I missed a crucial line:

> After device regains connection, success completion is fired without any problems.

What's happening here is that when you start an RPC, the client will get a _future_ connection to the server. The connection future will only be resolved with an active connection or a failed connection when we give up on the connection (i.e. no connection re-establishment). In your case you're seeing a transient failure: the connection attempt failed but we're waiting to try again; the future connection is yet to be resolved.

Meanwhile, the call object is waiting for this future. As long we continue trying to establish a connection the response future won't be resolved: it's still waiting for the call to start. As you noted: once the device regains connection, the connection future succeeds and the call fires as expected.

One option you do have here is setting a timeout on the call: if it's not completed before the timeout elapses then the response future will fail, even if the connection future is yet to be resolved.

**Comment by Lukasa** [comment] 2020-06-15 06:56
> Meanwhile, the call object is waiting for this future. As long we continue trying to establish a connection the response future won't be resolved: it's still waiting for the call to start. As you noted: once the device regains connection, the connection future succeeds and the call fires as expected.
> 
> One option you do have here is setting a timeout on the call: if it's not completed before the timeout elapses then the response future will fail, even if the connection future is yet to be resolved.

It's important to stress that this is the Apple recommendation for how to handle network connections on iOS devices: generally it is better to wait for connectivity in cases where you don't have it than to fail. This includes cases like VPN establishment, or circumstances where the user has prevent your app accessing some kinds of network interface which will require the system to establish new connections.

With that said, we should consider implementing analogous functionality to `URLSession`'s [`URLSessionConfiguration.waitsForConnectivity`](https://developer.apple.com/documentation/foundation/urlsessionconfiguration/2908812-waitsforconnectivity) and [`URLSessionTaskDelegate.urlSession(_:taskIsWaitingForConnectivity)`](https://developer.apple.com/documentation/foundation/urlsessiontaskdelegate/2908819-urlsession). This would allow you to observe the "waiting" state in your delegate and provide more helpful UIs to your users, without setting timeouts.

This would require some basic changes in SwiftNIO Transport Services as well as here (apple/swift-nio-transport-services#94), but it's probably the ideal from a usability perspective.

**Comment by IgorRosocha** [comment] 2020-06-16 13:24
@glbrntt thank you very much for your fast and relevant feedback! Now I understand exactly what is happening under the hood, and timeout is what I've been looking for.

> With that said, we should consider implementing analogous functionality to URLSession's URLSessionConfiguration.waitsForConnectivity and URLSessionTaskDelegate.urlSession(_:taskIsWaitingForConnectivity). This would allow you to observe the "waiting" state in your delegate and provide more helpful UIs to your users, without setting timeouts.

While in my specific case this would not be an option, I totally agree that it would be helpful to be able to observe the waiting state.

Thanks guys for your feedback and for constant improvement of gRPC Swift!

**Comment by glbrntt** [comment] 2020-06-17 08:59
No problem -- I'm going to close this in favour of #844.

**Closed by glbrntt** 2020-06-17 08:59 UTC
Labels: nio, question
