### ISSUE TITLE
Support for pod.

### ISSUE THREAD

**Issue by luca3104** [grpc/grpc-swift#45] opened 2017-04-25 03:09 UTC
When grpc-swift support for pod? 
master branch podspec name have "incomplete".

**Comment by takemiyamakoto** [comment] 2017-04-25 04:17
It would be great to have this soon, as we are using it in Hyperledger Iroha.

**Comment by johndpope** [comment] 2017-04-26 14:48
there is a swift build package / but it has problems with linking libz.tbd - until this resolves - this is a blocker.

**Comment by johndpope** [comment] 2017-04-28 19:04
@luca3104  in your podfile you can specify a specific git commit

eg.
pod 'SwiftGRPC', :git => 'git@github.com:grpc/grpc-swift.git', :commit => '6022ef1'


try that

**Comment by luca3104** [comment] 2017-04-29 04:59
Thanks.

**Comment by sashabaranov** [comment] 2017-05-12 14:12
@johndpope this yields `redefenition of module 'openssl'` in BoringSSL to me.

**Comment by sashabaranov** [comment] 2017-05-12 14:14
Probably due to old version of BoringSSL?

```
Analyzing dependencies
Pre-downloading: `SwiftGRPC` from `git@github.com:grpc/grpc-swift.git`, commit `6022ef1`
[!] Unable to satisfy the following requirements:

- `BoringSSL (~> 8.2)` required by `Podfile`
- `BoringSSL (~> 7.0)` required by `gRPC-Core/Implementation (1.0.2)`
```

**Comment by DamirDiz** [comment] 2017-05-19 09:46
Using the Swift Package Manager is really a nightmare. pod support would be amazing

**Comment by johndpope** [comment] 2017-05-19 14:04
Presumably from title of cocoapod somethings missing as it's 'incomplete'. so these helpers may get nowhere. I haven't used this - am using SPM. these are some stabs in the dark. 
you could try 

pod update

does it help to force these lines into podfile?
pod 'BoringSSL', '~> 8.2'
pod 'SwiftGRPC', :git => 'git@github.com:grpc/grpc-swift.git', :commit => '6022ef1'

(lastly - if all that don't work - you could try updating brew / cocoapods - beware of changes in osx)
https://github.com/johndpope/updater-for-macos

**Comment by msalman86** [comment] 2017-06-12 15:09
did anyone get it to work with pod?

**Comment by dhavalcue** [comment] 2017-08-13 02:11
Any plans to fix this? Excited about integrating this into our project, however it has been a painful process.

**Comment by mosn** [comment] 2017-08-15 06:13
bump! 

I think most issue is related to version dependence in podSpec for Core-GRPS. I tries to bump bump the version so that I can install newer version of `BoringSSL` but that also cause a lot of issue with the other dependencies. 

Would be great if we can have this fixed

**Comment by bootstraponline** [comment] 2017-09-30 18:20
Cocoapods support would be amazing. [apple/swift-protobuf](https://github.com/apple/swift-protobuf) is supporting Cocoapods already.

**Comment by bootstraponline** [comment] 2017-09-30 20:14
## Summary of the issue

[SwiftGRPC-incomplete.podspec](https://github.com/grpc/grpc-swift/blob/master/SwiftGRPC-incomplete.podspec) references a very old `gRPC-Core` version. Updating to the latest `gRPC-Core (1.6.0)` helps. There are still compile errors on Xcode 9 though:

<img width="464" alt="xcode_9_grpc_swift" src="https://user-images.githubusercontent.com/1173057/31049113-3f6f0504-a5fa-11e7-85ea-ff625c46f9d0.png">

Cocoacods is completely broken with `grpc-swift` sadly. 😭

**Comment by vanshg** [comment] 2017-11-20 07:28
+1

**Comment by vanshg** [comment] 2017-11-20 07:29
Is there any timeline for when CocoaPods will be officially supported?

**Comment by MrMage** [comment] 2018-02-19 15:57
I have prepared a podspec that seems to work for me. See https://github.com/grpc/grpc-swift/issues/111#issuecomment-366733622 on how to try it out. (Also, I'd suggest closing this as a duplicate of #111.)

**Closed** 2018-04-12 21:36 UTC
