### ISSUE TITLE
Generic client interceptors

### ISSUE THREAD

**Issue by achew22** [grpc/grpc-swift#1417] opened 2022-05-29 21:45 UTC
### Is your feature request related to a problem? Please describe it.

It requires a great deal of boilerplate to create an interceptor that works on every method, in addition to being easy to forget a method. That boilerplate is repeated for every method on every service that exists in a codebase. It would be nice if there was a way to create an interceptor that could be installed on any client without specializing.

The specific use case that I have is that I would like to attach `authorization` headers to every request that comes out of my app. While I can, and do presently, manually attach that header to every request, I inevitably spend non-trivial time trying to debug every new RPC I add.

### Describe the solution you'd like

I would like to see a way to make a "generic" interceptor. This could either be an interceptor factory that implements the protocol for every service, or any other scheme that would allow for manipulating requests before they go out over the wire.

### Describe alternatives you've considered

* Manually injecting the `authorization` header into every RPC/manually implementing every interceptor factory protocol. `<-- current solution`
* Writing a `protoc` plugin that generates an "adapter" for each method on each service that allows you to install any class that implements `class Interceptor<Request: Message, Response: Message>:
  ClientInterceptor<Request, Response>` or some similar type.
* Writing a custom implementation of `Channel` that allows such hooks.

### Additional context

It's entirely possible, maybe even likely, that this can be done right now but that I lack the type flexibility to come up with a clever solution to do it. If that's the case, can we treat this as a feature request for documentation around how one would create a generic client interceptor? Thank you!

**Comment by glbrntt** [comment] 2022-05-30 07:40
I agree that this is _much_ more cumbersome than it should be.

To the alternatives you've considered, wrapping a `GRPCChannel` may be the simplest way to achieve this. You can insert the additional headers in `makeCall` before calling forwarding to the 'real' `GRPCChannel` implementation.

Closing this as a duplicate of: https://github.com/grpc/grpc-swift/issues/1148

**Closed by glbrntt** 2022-05-30 07:40 UTC
Labels: enhancement
