### ISSUE TITLE
Carthage Support

### ISSUE THREAD

**Issue by soffes** [grpc/grpc-swift#13] opened 2017-01-11 17:24 UTC
It would be fantastic if you had Carthage support with pre-built binaries :heart:

**Comment by timburks** [comment] 2017-01-11 17:37
Noted - thanks!

**Comment by slessans** [comment] 2017-02-13 03:35
Any insight into how to do this would be greatly appreciated -- currently having lots of trouble trying to use this library from an iOS application.

**Comment by noppoMan** [comment] 2017-03-06 07:59
@timburks @soffes 
Hi, I tried to install grpc-swift via Carthage and it worked fine on my iPhone 7 plus.
(I also successfully archived/exported(ipa) and installed from ad-hoc with following flows)

Cartfile
```
github "apple/swift-protobuf" "0.9.24"
github "grpc/grpc-swift" "0.1.10"
```
and execute `carthage update --platform iOS`

## Adding Header Search Paths for CgRPC
<img width="779" alt="screen shot 2017-03-06 at 16 45 19" src="https://cloud.githubusercontent.com/assets/1511276/23600963/75388f6e-028c-11e7-9bb6-20729c12ebc8.png">

`$(SRCROOT)/Carthage/Checkouts/grpc-swift/Sources/CgRPC/include`

## Link Binary With Libraries Phase
<img width="961" alt="screen shot 2017-03-06 at 16 47 26" src="https://cloud.githubusercontent.com/assets/1511276/23600998/9e42d518-028c-11e7-9ddf-55df29de98d2.png">

## Run Script Phase
<img width="478" alt="screen shot 2017-03-06 at 16 48 18" src="https://cloud.githubusercontent.com/assets/1511276/23601033/c331ff84-028c-11e7-803c-d4021346000a.png">

Check this out If you are interested.
Actually I'm gonna use grpc-swift on my both of server and iOS project!

**Comment by ebriney** [comment] 2017-06-22 15:53
But there is no mac target though:
```
*** Skipped building grpc-swift due to the error:
Dependency "grpc-swift" has no shared framework schemes for any of the platforms: Mac

If you believe this to be an error, please file an issue with the maintainers at https://github.com/grpc/grpc-swift/issues/new
```

**Comment by noppoMan** [comment] 2017-06-26 07:42
@ebriney 
Currently grpc-swift does not have `.xcodeproj` cause this is a [SPM](https://github.com/apple/swift-package-manager) library. (It means this is not be able to install via Carthage)
If you wanna install this with Carthage, folk this and add xcodeproj with `swift package generate-xcodeproj`.

Or Try this https://github.com/noppoMan/grpc-swift
It has a xcodeproj that include some extra settings for iOS building and can install via Carthage.

**Comment by ebriney** [comment] 2017-06-27 07:59
Thanks, I will try that.

**Comment by willks** [comment] 2017-07-15 05:30
@noppoMan Thanks for your fork - I'm using it and it's very easy to get going thanks to the Carthage support! Cheers

**Comment by agirault** [comment] 2017-10-05 18:17
> Or Try this https://github.com/noppoMan/grpc-swift

@noppoMan: it seems @timburks showed interest. Would it make sense to create a PR with the `xcodeproj` to allow to use Carthage out of the box?

**Comment by xiaoyao250** [comment] 2017-11-23 07:43
@noppoMan Thanks you. 
Cartfile
```
github "apple/swift-protobuf"
github "grpc/grpc-swift"
```
execute `carthage update --platform iOS`
I can't get grpc frameworks. Do you know why?

**Comment by MikeSilvis** [comment] 2018-02-02 00:51
@timburks any update on this? It would help immensely for developing iOS apps

**Comment by SebastianThiebaud** [comment] 2018-02-06 00:30
I would love to see Carthage support for `grpc-swift`. Any update on this? I'd love to help if needed.

**Comment by SebastianThiebaud** [comment] 2018-02-27 06:36
@timburks We got a working fork for Carthage, but that implies some changes if we want the main repository https://github.com/grpc/grpc-swift to support Carthage. I don't know what's your position about supporting Carthage but I'd strongly encourage to enable it (more adoption of `grpc-swift` can only lead to a better quality of the library and more hands to help). I could help to get `grpc-swift` ready for Carthage. The only blocker that I see at the moment is related to `CZlib`. The dependency used (https://github.com/ZewoGraveyard/CZlib) wouldn't work at this point with Carthage. I also realized that this dependency hasn't been updated for over 2 years. Could we assume it won't be updated anymore and directly include the source code in this repository? If that's not something that seems good to you, we could make `CZlib` working with Carthage too.

**Comment by MrMage** [comment] 2018-02-27 09:41
Would another option be to simply avoid including zlib in your Carthage spec? For example, [in my grpc-swift Podspec](https://github.com/MrMage/grpc-swift/blob/podspec/SwiftGRPC.podspec) I include the necessary dependencies as other Pods instead of using any of the SPM packages or the vendored code. Given that zlib should be available on the Carthage-supported platforms anyway, maybe that would be another option?

**Actually, thinking more about this, is the zlib dependency still needed at all? With a cursory look through the framework, I can't find any code dependencies on zlib.**

**Comment by SebastianThiebaud** [comment] 2018-02-27 18:13
If we can confirm that `zlib` isn't needed, that would be great.

**Comment by MikeSilvis** [comment] 2018-02-27 18:20
@SebastianThiebaud check out https://github.com/noppoMan/grpc-swift

Using this fork, i was able to get grpc-swift to compile using Carthage

**Comment by SebastianThiebaud** [comment] 2018-02-27 18:22
@MikeSilvis This repo isn't having the latest changes for almost a year. I'm talking about having the official repository supporting Carthage. Like my initial message mentions, I already got a personal fork working with Carthage.

**Comment by MikeSilvis** [comment] 2018-02-27 18:28
Yes, i'm just confused as to what the blocker with `CZlib` is. Here is my own internal fork i use, and i have czlip compiling fine: https://github.com/mikeSilvis/grpc-swift/

**Comment by SebastianThiebaud** [comment] 2018-02-27 18:30
My point is that the `CZlib` repository used as dependency isn't compatible with Carthage. Cocoapods and Carthage do not require the same configuration.

**Comment by MikeSilvis** [comment] 2018-02-27 18:34
@SebastianThiebaud i highly suggest you checkout my fork and try using it with Carthage. I have `CZLib` working.

**Comment by SebastianThiebaud** [comment] 2018-02-27 18:36
Yes, I saw that you're using `CZlib` as a submodule. It is a possibility. Like I said, I already have a working version of this repo working with Carthage (include CZlib). Now, I'm having this discussion here to feel what's the best implementation that I could propose for Carthage so everyone is happy. Since you got Cocoapods support working for this repository, did you submit a PR for it?

**Comment by MikeSilvis** [comment] 2018-02-27 18:40
I have Carthage working, not Cocoapods

**Comment by MrMage** [comment] 2018-02-27 18:41
@SebastianThiebaud see #139. No mention of `zlib` whatsoever.

**Comment by SebastianThiebaud** [comment] 2018-02-27 18:44
Good to know @MrMage. I will try something a bit later today then.

**Comment by SebastianThiebaud** [comment] 2018-02-27 18:57
@MrMage I just updated the `Package.swift` file to remove `CZlib` from the list of dependencies. Turns out, it is still needed for `CgRPC`:
<img width="849" alt="screen shot 2018-02-27 at 10 57 26 am" src="https://user-images.githubusercontent.com/770074/36748563-05e7d184-1bad-11e8-9c10-857122b38eba.png">

**Comment by MrMage** [comment] 2018-02-27 19:11
Damn. Could you try using the system-provided zlib copy, though? (Linked with -lz)

**Comment by SebastianThiebaud** [comment] 2018-02-27 19:14
I will try this. Another limitation I just remembered: the way libs files (CgRPC, BoringSSL...) are included in the Xcode project is hard to maintain. `swift package generate-xcodeproj` can create the project and add the necessary files but Carthage needs a project file committed with a shared scheme.

**Comment by MikeSilvis** [comment] 2018-03-14 22:25
@MrMage @SebastianThiebaud any update on this? I see that Cocoapods support was added

**Comment by MrMage** [comment] 2018-03-14 22:30
I have a commit that removes the vendored zlib code (https://github.com/MrMage/grpc-swift/commit/263e66bad2e6db7853e719d2f271fed0952461ab). However, I don't use Carthage, so no idea what else would need to be done to get this usable for Carthage.

**Comment by willks** [comment] 2018-03-27 06:12
I'm tired of the manual tinkering - so I just swapped back to cocoapods. Not my preference, but I find I have a lot more coding time as opposed to build time issues (and script failures) with Carthage.

Waiting for Swift Package Manager once those lazy ass Apple guys do something about it for iOS.

**Comment by SebastianThiebaud** [comment] 2018-05-27 22:46
If you're interest, we're maintaining a branch for Carthage in a fork. https://github.com/postmates/grpc-swift/tree/carthage_structure

We've also updated the `Makefile` so the Xcode project doesn't need any manual operation to work with Carthage. https://github.com/postmates/grpc-swift/blob/carthage_structure/Makefile

**Comment by MrMage** [comment] 2018-05-28 08:16
Interesting! Do you think there would be a way to merge this upstream to give users the choice between CocoaPods and Carthage?

**Comment by SebastianThiebaud** [comment] 2018-05-29 03:50
I don't see any way to support Carthage if we don't commit the `.xcodeproj` file. And I believe we do not want to do this because of SPM, correct?

**Comment by MrMage** [comment] 2018-05-29 06:51
Does Carthage offer a "pre-build" step? In that case, could we have a "pre-build" script that has SPM generate the project on the fly and, if necessary, patches in the necessary scheme files?

**Comment by SebastianThiebaud** [comment] 2018-05-29 16:40
I wish, but it doesn't 😞

**Comment by JonasVautherin** [comment] 2018-08-06 23:15
Why is it not possible to support both the `.xcodeproj` and SPM? Isn't it what [RxSwift](https://github.com/ReactiveX/RxSwift) is doing? They have both `Rx.xcodeproj` and `Package.swift` at the root of the repo. Or did I miss something?

**Comment by MrMage** [comment] 2018-08-07 08:20
At that point we'd need to ensure that the Carthage `.xcodeproj` is always kept up-to-date. I am open to this, as long as that work can be done automatically. E.g. by having a script that auto-generates an `.xcodeproj` via SPM, renames it (to avoid conflicts with the regular SPM one), then applies Carthage-related patches and commits the result.

**Comment by JonasVautherin** [comment] 2018-08-07 11:56
Right, I played a bit more with it, and it is not so straightforward. Especially because I am building for iOS. So I'll give up on Carthage for now.

**Comment by MrMage** [comment] 2018-08-07 12:03
What extra complications does building for iOS cause in this case? We are interested in improving the developer experience using SwiftGRPC on iOS, so maybe there are some thing we can improve on here.

**Comment by JonasVautherin** [comment] 2018-08-07 12:47
I have, I believe, two main issues for Carthage (note: I am on tag 0.4.2).

1. I need to run `$ make && make project` before I can run `xcodebuild`.
2. Not all the gRPC-Swift targets can be built for iOS: building manually, I run something like `$ xcodebuild -target BoringSSL -target SwiftGRPC -target SwiftProtobuf -target CgRPC ... -sdk iphoneos`, because when running `$ xcodebuild -alltargets -sdk iphoneos`, it fails to build.

I read a lot on the Carthage issues/discussions, and I don't believe they would be open to add a possibility to have a "prebuild script" (in this case `$ make && make project`) that would be run by Carthage. Which means that either gRPC-Swift would need to version the files created by `$ make && make project`, which is really not convenient, or I would need to fork gRPC-Swift to do it, and that's not much better (but still okay, I guess).

And more importantly, I don't think Carthage is planning to add a way to select which targets to build. There have been many discussions, people have been wanting that for years, have been arguing and all, so I would not count on that anytime soon.

It feels like Carthage works well when you have an `.xcodeproj`, can build all the schemes for all platforms from that directly and expect your clients to depend on all your schemes. But you don't have any more control than that, so for a repo like gRPC-Swift, it just becomes painful to use/maintain. So I will stay with Cocoapods and my manual scripts for people not wanting to use Cocoapods :-).

**Comment by MrMage** [comment] 2018-08-07 12:51
Thanks for the elaboration!

As I mentioned before, I _might_ be okay with maintaining a versioned variant of the `.xcodeproj` under a different name as long as that project could be generated automatically, e.g. before committing. In theory, we could adapt the script that generates that project to automatically delete all non-Carthage targets using the Ruby `xcodeproj` gem (we already use it to adjust tab widths in `make project`).

**Comment by JonasVautherin** [comment] 2018-08-07 13:10
Yeah but at some point, if Carthage requires hacks everywhere in the project, I am not sure if it is really worth it.

For instance, what are "non-Carthage" targets? Maybe people actually want to build all targets for macOS, and only iOS depends solely on `BoringSSL`, `SwiftGRPC`, `CgRPC` and `SwiftProtobuf`.

**Comment by MrMage** [comment] 2018-08-07 15:03
I think the things that need to built for Carthage are identical on iOS and Mac (the ones you named). For the rest, we can keep asking users to clone the repo separately and use SPM. With CocoaPods, they also need to clone the repo and build the `protoc` plugin with SPM, we could adopt the same for Carthage.

Depends on how many hacks would be needed to make the Carthage project work, of course. My stance is more like "If a Carthage users wants this so badly that they would build it the way I described above, then we can probably accomodate for it". I'm not going to go out and build it for them right now ;-)

**Comment by JonasVautherin** [comment] 2018-08-21 11:14
Well, actually it doesn't work (see [here](https://github.com/Carthage/Carthage/issues/2559)) :disappointed:.

It works for the simulator, but there seems to be a signing problem somewhere that I don't understand.

**Comment by JonasVautherin** [comment] 2018-08-21 17:44
I was not using Carthage's `copy-framework` in the project depending on Carthage! So it actually works.

[Here](https://github.com/dronecode/dronecodesdk-swift-example) is an example project that works with grpc-swift! I also have 2 other projects where people have been able to use the Carthage integration, so I would say it is finally working 🎉.

**Comment by MrMage** [comment] 2018-08-22 06:53
Sorry, is this still working? ;-)

I noticed some changes between "working" and "not working"; please let me know if everything is working now and whether we need to update some code or documentation on the SwiftGRPC side for full Carthage compatibility.

**Comment by JonasVautherin** [comment] 2018-08-22 08:32
It is working.

I thought it was not, but it was my fault as a Carthage user, and not a bug in the SwiftGRPC setup.

And now I have other developers who have been using it in other projects and who confirmed that it works for them :-).

**Comment by MrMage** [comment] 2018-08-22 08:33
Thanks for the heads-up! Closing this; let me know (or file a new issue) in case you do encounter problems in the future.

**Closed by MrMage** 2018-08-22 08:33 UTC
Labels: enhancement

**Comment by sbarow** [comment] 2018-11-06 17:39
Is this task resolved and is Carthage officially supported now? Not able to get this to build using `carthage update --platform iOS`

Carthage: `0.31.2`
Tried with: 
`github "grpc/grpc-swift" "23a0ebdee9613f615f2f2469ed3e700df5856417"`
`github "grpc/grpc-swift" "0.6.0" `
`github "grpc/grpc-swift" "0.5.1" `

**Comment by JonasVautherin** [comment] 2018-11-07 18:12
@sbarow: Are you on Xcode 10?

Somehow it doesn't build with Xcode 10, and I haven't understood why yet. Xcode 9.4.1 works, though. I'm not sure what Xcode 10 is doing but it somehow changes the `path = ".build/checkouts/swift-protobuf.git-<hash>` in the project file and then doesn't find it -_-.

**Comment by MrMage** [comment] 2018-11-07 18:16
@JonasVautherin could it be that the paths generated by `swift resolve` are different for Xcode 10 vs. 9.4? Or maybe Xcode 10/Swift 4.2 simply doesn't generate deterministic paths for the dependencies, while 9.4/Swift 4.1 does? That would also explain why I never was able to create a working Carthage project for the NIO branch.
